export {
    REFRESH_CHANNELS_COMMAND,
    REFRESH_CHANNELS_COMMAND_RESULT,
    UNSUBSCRIBE_COMMAND,
    UNSUBSCRIBE_COMMAND_RESULT,
    SUBSCRIBE_COMMAND,
    SUBSCRIBE_COMMAND_RESULT};

const REFRESH_CHANNELS_COMMAND="get_subscriptions";
const REFRESH_CHANNELS_COMMAND_RESULT="get_subscriptions_result";
const UNSUBSCRIBE_COMMAND="unsubscribe";
const UNSUBSCRIBE_COMMAND_RESULT="unsubscribe_result";
const SUBSCRIBE_COMMAND="subscribe";
const SUBSCRIBE_COMMAND_RESULT="subscribe_result";