"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MESSAGE_CONTENT = exports.CHANNEL_ID = exports.UNSUBSCRIBE_BUTTON_COMMAND = exports.USER = exports.ID = exports.CURRENT_CHANNEL = exports.SOCKET_COMMAND = exports.KIND = exports.TOPIC = exports.CHANNEL = void 0;
var CHANNEL = "channel";
exports.CHANNEL = CHANNEL;
var CURRENT_CHANNEL = "current_channel";
exports.CURRENT_CHANNEL = CURRENT_CHANNEL;
var MESSAGE_CONTENT = "content";
exports.MESSAGE_CONTENT = MESSAGE_CONTENT;
var TOPIC = "topic";
exports.TOPIC = TOPIC;
var KIND = "kind";
exports.KIND = KIND;
var SOCKET_COMMAND = "socket_command";
exports.SOCKET_COMMAND = SOCKET_COMMAND;
var ID = "id";
exports.ID = ID;
var USER = "user";
exports.USER = USER;
var UNSUBSCRIBE_BUTTON_COMMAND = "unsubscribe_button_command";
exports.UNSUBSCRIBE_BUTTON_COMMAND = UNSUBSCRIBE_BUTTON_COMMAND;
var CHANNEL_ID = "channelId";
exports.CHANNEL_ID = CHANNEL_ID;
